BEGIN TRANSACTION;

INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 3, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607573500/3/yi2wwpz37sedzb8eujko.jpg', 'sheep.jpg', '3/yi2wwpz37sedzb8eujko', 'my sheeps', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 3, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607573532/3/mwaa6n4pmzdpcyypeule.jpg', 'bike.jpg', '3/mwaa6n4pmzdpcyypeule', 'red bike', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 3, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574059/3/zgqnlklydhkrppoomy1y.jpg', 'bicycle.jpg', '3/zgqnlklydhkrppoomy1y', 'red bike', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 3, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574078/3/xqmz9fieg8d1conmztsk.jpg', 'boy-snow-hoodie.jpg', '3/xqmz9fieg8d1conmztsk', '', true);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 3, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574091/3/ngihonkghsvthrth2lll.jpg', 'jazz.jpg', '3/ngihonkghsvthrth2lll', '', true);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 4, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574173/4/waqhjmnhecqtuyomih9c.jpg', 'kitchen-bar.jpg', '4/waqhjmnhecqtuyomih9c', 'cook', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 4, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574191/4/nfpfdlpl2ybm8r6vzmdu.jpg', 'smiling-man.jpg', '4/nfpfdlpl2ybm8r6vzmdu', '', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 4, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574227/4/xz7fjwvhu2bojdtwyorx.jpg', 'nature-mountains.jpg', '4/xz7fjwvhu2bojdtwyorx', '', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 4, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574237/4/g1hcv2ltr2bc7tq38gbv.jpg', 'girl-urban-view.jpg', '4/g1hcv2ltr2bc7tq38gbv', '', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 4, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574282/4/bfu0tdnvlbvr9i42e4wo.jpg', 'architecture-signs.jpg', '4/bfu0tdnvlbvr9i42e4wo', '', true);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 4, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574357/4/zmmo04gwgvdheou28pkp.jpg', 'beach-boat.jpg', '4/zmmo04gwgvdheou28pkp', '', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 5, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574392/5/icv72lcynltpie0ahzwh.jpg', 'dessert.jpg', '5/icv72lcynltpie0ahzwh', '', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 5, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574424/5/rc5sotwydcrtea3ouhtw.jpg', 'fish-vegetables.jpg', '5/rc5sotwydcrtea3ouhtw', 'fish', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 5, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574451/5/fimjg7c4iedjfzkzzryg.jpg', 'pot-mussels.jpg', '5/fimjg7c4iedjfzkzzryg', 'love mussels', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 5, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574463/5/ev27myglfexomdwjp5pd.jpg', 'spices.jpg', '5/ev27myglfexomdwjp5pd', '', true);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 1, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574486/1/ebnrutmrrhaa8d7fpqyr.jpg', 'cat.jpg', '1/ebnrutmrrhaa8d7fpqyr', '', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 1, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574533/1/bdhrxjcitqrwojsvlzod.jpg', 'reindeer.jpg', '1/bdhrxjcitqrwojsvlzod', 'deer', false);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 1, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607574554/1/tuarjpgb2e1bkqhzk1ho.jpg', 'three-dogs.jpg', '1/tuarjpgb2e1bkqhzk1ho', 'my dogs', true);
INSERT INTO public.pictures ( user_id, pic_url, pic_name, pic_server_name, description, private) VALUES ( 1, 'https://res.cloudinary.com/dr1xyxwvj/image/upload/v1607658371/6/otwrz1srklxenfwd83pp.png', 'Titatnic.jpg', '1/tuarjpgb2e1bkqhzk1ho', 'my dogs', true);


INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'my list', 3);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'favorite', 4);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'looks good', 5);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'picture', 3);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'nice', 3);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'interesting', 5);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'fantastic', 4);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'great', 4);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'groovy', 5);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'mesmerizing', 5);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'nice shot', 3);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'slay', 4);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'masterpiece', 5);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'goodness', 3);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'well-done', 4);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'game time', 3);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'outlook', 4);
INSERT INTO public.favorites ( fav_name, user_id) VALUES ( 'another one', 4);


INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (1, 1);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (1, 2);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (1, 3);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (1, 4);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (2, 18);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (3, 10);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (6, 11);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (4, 12);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (5, 13);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (7, 14);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (8, 15);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (9, 16);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (10, 9);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (11, 17);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (18, 8);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (17, 7);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (16, 6);
INSERT INTO public.favorite_picture (favorite_id, picture_id) VALUES (5, 5);


INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 1, 2, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 2, 1, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 3, 1, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 3, 3, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 3, 4, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 3, 5, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 4, 5, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 6, 5, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 6, 1, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 6, 3, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 7, 4, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 7, 5, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 7, 1, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 5, 4, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 5, 5, 3);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 5, 3, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 5, 1, 2);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 8, 1, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 8, 3, 2);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 8, 4, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 8, 5, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 9, 5, 2);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 9, 1, 3);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 9, 3, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 9, 4, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 10, 3, 3);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 10, 4, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 10, 5, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 11, 3, 2);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 11, 1, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 11, 4, 3);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 11, 5, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 12, 1, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 12, 3, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 12, 4, 3);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 13, 5, 1);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 13, 4, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 13, 3, 5);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 13, 1, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 13, 5, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 14, 5, 3);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 14, 4, 4);
INSERT INTO public.ratings ( picture_id, user_id, rating) VALUES ( 14, 1, 2);



INSERT INTO public.likes ( picture_id, user_id) VALUES ( 1, 4);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 1, 5);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 1, 1);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 2, 1);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 2, 5);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 2, 4);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 2, 3);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 10, 3);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 10, 4);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 10, 5);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 10, 1);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 11, 1);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 11, 3);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 11, 4);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 11, 5);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 9, 5);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 9, 4);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 8, 3);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 8, 4);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 7, 1);
INSERT INTO public.likes ( picture_id, user_id) VALUES ( 7, 3);


INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 7, 1, 'good picture');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 7, 2, 'agreed good picture');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 7, 3, 'average picture');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 8, 3, 'average picture');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 8, 4, 'abcd picture');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 8, 5, 'What else is new?');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 9, 4, 'Caption that!');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 9, 4, 'Houston, we have a problem');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 9, 3, 'I could take a better shot!');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 10, 3, 'lemme see what we got here...');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 10, 4, 'nice');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 10, 1, 'looks good');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 10, 2, 'This comment doesnt make any sense');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 11, 4, 'lol');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 11, 1, 'Hit me up whoever took this picture');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 11, 3, 'Why doesnt this app have emojis?');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 11, 5, 'I want another album from Odesza');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 12, 3, 'Do you know who you are?');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 12, 4, 'Cannot wait for this pandemic to be over');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 12, 5, 'I love EDM');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 13, 3, 'Steak should be cooked medium-rare');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 13, 4, 'When am I gonna get a job?');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 13, 5, 'I want a spaceship');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 14, 4, 'Netflix and chill');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 14, 5, 'If I become rich I will sell this app to myself and donate the money');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 14, 3, 'Craving ice is a sympton of iron deficiancy');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 14, 1, 'There are more life forms on your body than people on Earth');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 15, 1, 'Snakes can predict earthquakes');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 15, 5, 'Volkswagen also makes sausages');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 15, 4, 'Sausage party is a funny cartoon!');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 16, 3, 'A ship, a duck and a rooster were the fisrt passengers in a hot air balloon');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 16, 4, 'Ducks in apples are delicious!');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 16, 1, 'Skydiving is breathtaking');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 17, 3, 'High heels were first designed for men');
INSERT INTO public.comments ( picture_id, user_id, comment) VALUES ( 17, 3, 'Some are still wearing them today');


COMMIT TRANSACTION;
